### ISSUE TITLE
Correção Exercício `0.7.1`

### ISSUE THREAD

**Issue by mathiasgheno** [dudununes15/dw23#3]
# Correção Exercício `0.7.1`

> Faça o layout do wireframe abaixo usando flexbox.  [Referência visual](https://i.imgur.com/jDDModP.png). 

Faltou aplicar uma largura para sua modal, definir uma borda e colocar um padding. 

```css
.container {
   width: 600px;
   border: 1px solid;
   padding: 10px;
}
```

**Nota:** 9
